### ISSUE TITLE
Logger outputs empty object for error object

### ISSUE THREAD

**Issue by skgndi12** [MovieReviewComment/Mr.C#85]
# 문제 상황
`logger` 에서 `Error` 객체를 empty object 로 출력하고 있음.  `logger` 를 구현하기 위해 사용한 `winston` 에서 `Error` 객체를 핸들링하는데 문제가 있는 것으로 확인. [관련 이슈](https://github.com/winstonjs/winston/issues/1338)

# 비교 케이스
> [!NOTE]  
> 출력 예시는 가독성을 위해 출력 내용을 다듬은 내용입니다. 데이터는 동일하지만 출력 형식은 상이함을 알립니다.

### 예시 상황
```typescript
logger.error(new Error('test'))
```

### TEXT

__기대한 내용__
```bash
[2023-12-14 16:51:26][error]: test {
  "stack": "Error: test\n    at main (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:59:16)\n    at Object.<anonymous> (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:71:3)\n    at Module._compile (node:internal/modules/cjs/loader:1254:14)\n    at Module.m._compile (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n    at Object.require.extensions.<computed> [as .ts] (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1117:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at phase4 (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/bin.ts:649:14)",
  "deployment": "dev"
}
```

__실제 내용__
```bash
[2023-12-14 17:40:45][error]: test {
  "deployment": "dev"
}
```

### JSON

__기대한 내용__
```bash
{
  "deployment": "dev",
  "level": "error",
  "message": "test",
  "stack": "Error: test\n    at main (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:59:16)\n    at Object.<anonymous> (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:71:3)\n    at Module._compile (node:internal/modules/cjs/loader:1254:14)\n    at Module.m._compile (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n    at Object.require.extensions.<computed> [as .ts] (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1117:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at phase4 (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/bin.ts:649:14)",
  "timestamp": "2023-12-14 16:52:15"
}
```

__실제 내용__
```bash
{
  "deployment": "dev",
  "level": "error",
  "timestamp": "2023-12-14 17:41:41"
}
```

### 비교 결과
 TEXT 에서는 에러의 메시지만 출력되고 stack 이 없는 채로 출력됨.  JSON 형식에서는 에러 정보가 완전히 누락된 채로 출력됨.

### 예시 상황
```typescript
logger.error('meta include error', new Error('test'));
```

### TEXT

__기대한 내용__
```bash
[2023-12-14 16:57:16][error]: meta include error test {
  "deployment": "dev",
  "stack": "Error: test\n    at main (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:59:38)\n    at Object.<anonymous> (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:71:3)\n    at Module._compile (node:internal/modules/cjs/loader:1254:14)\n    at Module.m._compile (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n    at Object.require.extensions.<computed> [as .ts] (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1117:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at phase4 (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/bin.ts:649:14)"
}
```

__실제 내용__
```bash
[2023-12-14 17:43:33][error]: meta include error test {
  "deployment": "dev",
  "stack": "Error: test\n    at main (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:62:38)\n    at Object.<anonymous> (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:82:3)\n    at Module._compile (node:internal/modules/cjs/loader:1254:14)\n    at Module.m._compile (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n    at Object.require.extensions.<computed> [as .ts] (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1117:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at phase4 (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/bin.ts:649:14)"
}
```

### JSON

__기대한 내용__
```bash
{
  "deployment": "dev",
  "level": "error",
  "message": "meta include error test",
  "stack": "Error: test\n    at main (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:59:38)\n    at Object.<anonymous> (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:71:3)\n    at Module._compile (node:internal/modules/cjs/loader:1254:14)\n    at Module.m._compile (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n    at Object.require.extensions.<computed> [as .ts] (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1117:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at phase4 (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/bin.ts:649:14)",
  "timestamp": "2023-12-14 16:53:48"
}
```

__실제 내용__
```bash
{
  "deployment": "dev",
  "level": "error",
  "message": "meta include error test",
  "stack": "Error: test\n    at main (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:62:38)\n    at Object.<anonymous> (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:82:3)\n    at Module._compile (node:internal/modules/cjs/loader:1254:14)\n    at Module.m._compile (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n    at Object.require.extensions.<computed> [as .ts] (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1117:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at phase4 (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/bin.ts:649:14)",
  "timestamp": "2023-12-14 17:42:25"
}
```

### 비교 결과
TEXT 및 JSON 형식 모두 기대한대로 에러가 포함되어서 출력됨.

### 예시 상황

```typescript
 logger.error('attribute in meta include error', { error: new Error('test') });
```

### TEXT

__기대한 내용__
```bash
[2023-12-14 17:45:56][error]: attribute in meta include error test {
  "deployment": "dev",
  "error": {
    "stack": "Error: test\n    at main (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:62:50)\n    at Object.<anonymous> (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:82:3)\n    at Module._compile (node:internal/modules/cjs/loader:1254:14)\n    at Module.m._compile (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n    at Object.require.extensions.<computed> [as .ts] (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1117:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at phase4 (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/bin.ts:649:14)"
  }
}
```

__실제 내용__
```bash
[2023-12-14 17:39:12][error]: attribute in meta include error {
  "deployment": "dev",
  "error": {}
}
```

### JSON

__기대한 내용__
```bash
{
  "deployment": "dev",
  "level": "error",
  "message": "attribute in meta include error test",
  "error": {
    "stack": "Error: test\n    at main (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:62:50)\n    at Object.<anonymous> (/Users/gimseong-won/coding/Mr.C/api/src/main.ts:82:3)\n    at Module._compile (node:internal/modules/cjs/loader:1254:14)\n    at Module.m._compile (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1618:23)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n    at Object.require.extensions.<computed> [as .ts] (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/index.ts:1621:12)\n    at Module.load (node:internal/modules/cjs/loader:1117:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:958:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at phase4 (/Users/gimseong-won/coding/Mr.C/api/node_modules/ts-node/src/bin.ts:649:14)"
  },
  "timestamp": "2023-12-14 17:48:01"
}
```

__실제 내용__
```bash
{
  "deployment": "dev",
  "error": {},
  "level": "error",
  "message": "attribute in meta include error",
  "timestamp": "2023-12-14 17:37:18"
}
```

### 비교 결과
TEXT 및 JSON 형식 모두 에러가 비어있는 객체로 출력됨.

**Comment by skgndi12** [comment]
참고 내용:
- https://github.com/winstonjs/winston/issues/1338
- https://betterstack.com/community/guides/logging/how-to-install-setup-and-use-winston-and-morgan-to-log-node-js-applications/#logging-errors-in-winston
- https://medium.com/@stieg/winston-3-and-logging-error-stacks-cf70b2111289
